[workspace]
authors = ["devops_bot <noreply@bot.ai>"]
channels = ["conda-forge"]
name = "chroma-editor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
openai = ">=1.91.0,<2"
pixi-kernel = ">=0.6.3,<0.7"

[pypi-dependencies]
streamlit = "*"
chromadb = "*"